### ISSUE TITLE
messaging

### ISSUE THREAD

**Issue by jdalton** [juliangruber/isarray#10]
Hi @juliangruber!

With IE < 11 no longer supported by MS & IE 8 being the last browser that needed `Array.isArray` would you be up for adding a [npm deprecate](https://docs.npmjs.com/cli/deprecate) message encouraging folks to use `Array.isArray`?

**Comment by juliangruber** [comment]
yeah, according to http://caniuse.com/usage-table IEs<9 make up only 0.6% of the browser marker. I'd be down with publishing a new major with the deprecation warning...just so we don't annoy the ecosystem of modules already depending on this, but don't encourage any new modules written to use this. sounds good?

**Comment by jdalton** [comment]
Sounds great!

**Comment by kgryte** [comment]
@juliangruber I would recommend against deprecating. People may use this module for reasons other than just as a polyfill. For example, because they prefer a) a more functional approach, b) an approach more amenable to proxying during tests, and c), more generally, dependency injection over globals.

**Comment by jdalton** [comment]
@kgryte I think that extends past the scope and general use of this package. I suspect folks grab for things like `isarray` because they don't know it's available in the language.

**Comment by kgryte** [comment]
@jdalton Without any statistics to back up your claim regarding general use, that is your opinion. I use this module and others like it for the reasons I mentioned earlier and I am fully aware that `Array.isArray` is available in the language.

**Comment by jdalton** [comment]
You can always use v1 of this package.

**Comment by juliangruber** [comment]
I'm with @jdalton here, `Array.isArray` _is_ javascript. If you _do_ want to avoid all globals (except for the module system which you can't avoid anyways), I suggest you check out https://github.com/raynos/global.

**Comment by juliangruber** [comment]
@jdalton should we deprecate in code or in npm? I feel like npm is cleaner.

**Comment by rands0n** [comment]
@kgryte I agree with you, in my case I like a more functional approach. And I put this part of package in util. In my case I need support of IE < 9.

You can check it out the util [version that I use here](https://github.com/rands0n/mangoo/blob/master/src/lang/isArray.js). From now on(if the project dont need old browsers :D), I would use `Array.isArray` from _Javascript_.

**Comment by jdalton** [comment]
@juliangruber 
> should we deprecate in code or in npm? I feel like npm is cleaner.

The npm route 👍 . In my mind it would be a combo of an up front readme notice and an [npm deprecate](https://docs.npmjs.com/cli/deprecate) message.

**Comment by jdalton** [comment]
That said, I guess the code could be simplified to `module.exports = Array.isArray` too.

**Comment by juliangruber** [comment]
Published `isarray@2.0.0` with deprecation message "Just use Array.isArray directly". Thanks @jdalton!

**Comment by jdalton** [comment]
:metal: I'll deprecate [lodash.isarray](https://www.npmjs.com/package/lodash.isarray) too!
