### ISSUE TITLE
Promise support?

### ISSUE THREAD

**Issue by watson** [juliangruber/isarray#11]
It is the future of javascript!

**Comment by juliangruber** [comment]
PRs welcome :)

**Comment by jondubois** [comment]
@watson @juliangruber Great... I'm working on a PR now.

Also, to build on top of this, I was thinking that maybe if `arr` is an array of Stripe tokens, we could send it off to a remote service to perform "extra checking"?

I hear https://givemeyourstripetokens.io is pretty popular these days ;p

**Comment by Ayesh** [comment]
For this remote service, make sure to use http instead of https. My roommate Jack and Jeff from the coffee shop next door agreed to cache results so it's faster to validate.

**Comment by Rudxain** [comment]
Also make it crash if it detects that the connection is made through LAN or WPA3 WiFi, and ask the user to use WPA, or better yet **WEP**. If the array has plaintext passwords, make sure to post them to Pastebin

**Comment by ljharb** [comment]
yes yes, you're all burgeoning comedians
