### ISSUE TITLE
Undeprecate

### ISSUE THREAD

**Issue by mcollina** [juliangruber/isarray#17]
We are getting some traffic on readable-stream because this is depreacted. However, we need this to support depreacted platforms. Can we remove the deprecate notice?

**Comment by juliangruber** [comment]
at this point i don't care any more, it has been deprecated for long enough, so yes I'm fine with undeprecating if this makes it easier for readable-stream. will do.

**Comment by juliangruber** [comment]
it's undeprecated

**Comment by mcollina** [comment]
Thanks!
Il giorno mer 12 lug 2017 alle 07:37 Julian Gruber <notifications@github.com>
ha scritto:
