### ISSUE TITLE
Testing Node, not own code

### ISSUE THREAD

**Issue by InPermutation** [juliangruber/isarray#2]
### Steps to reproduce

Change index.js to

``` js
module.exports = Array.isArray || function() { return true; };
```

Run `npm test`.
### Observe

All of the tests pass
### Expected

About half of the tests fail

**Comment by juliangruber** [comment]
this is also being run in browsers, see: https://ci.testling.com/juliangruber/isarray

i think what we really need is a test:browser target that uses tape-run or something to launch the test in an old browser

**Comment by ljharb** [comment]
While it'd be great to also test in browsers, this is something we'll always accept a PR for, and nothing we need an open issue for.
