### ISSUE TITLE
Potential problem in some environments

### ISSUE THREAD

**Issue by daniel-white** [juliangruber/isarray#32]
```
isarray({ 
   toString: function() {
      return '[object Array]'
   }
});
```

**Comment by juliangruber** [comment]
This returns `false` in Chrome and node, which environment did you test this in? Or did you expect it to return true?

You can test the approach like this:

```js
({}).toString.call({ toString: () => '[object Array]' }) === '[object Array]'
false
```

**Comment by juliangruber** [comment]
That's why we use `toString` from the `Object` prototype, and not the value passed.

**Comment by daniel-white** [comment]
Totally missed that line. Closing.
