### ISSUE TITLE
`TypedArray` support?

### ISSUE THREAD

**Issue by Rudxain** [juliangruber/isarray#35]
```js
isArray(new Uint8Array(0)) // false
```
I know this is technically correct, but what if this library exported 1 more module function to check if the value is a `TypedArray`?

**Comment by ljharb** [comment]
That already exists: https://npmjs.com/is-typed-array and https://npmjs.com/which-typed-array.

This package is best kept simple.

**Comment by Rudxain** [comment]
> This package is best kept simple

I agree, and now I agree even more after looking at the source files. Thank you for the info
